version: '3'
services:
    app:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: app
      restart: unless-stopped
      user: www-data      
      volumes:
        - ./:/var/www/html
      networks:
        - laravel-network
    nginx-server:
      image: nginx:latest
      container_name: nginx-server
      restart: unless-stopped
      ports:
        - 8111:80
      volumes:
        - ./:/var/www/html
        - ./default.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - app
      networks:
        - laravel-network
networks:
  laravel-network:
